name: "e2e"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: test-action
        uses: ./
        with:
          base_ref: 027b33661ae3211230e8cd03d19df49ba620b379
          head_ref: ${{ github.sha }}
          kustomizations: |-
            testdata/prod
            testdata/stage
            testdata/new
      - uses: mshick/add-pr-comment@v2
        with:
          message: ${{ steps.test-action.outputs.diff }}
