name: "e2e"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: test-action
        uses: ./
      - run: echo "${{ steps.test-action.outputs.diff }}"
